###################################################
###### Makefile for Classical Hydrodynamics #######
###################################################

ifeq ($(HYDRO),True)
   include $(AZTPATH)/Src/physics/HD/HYDRO/Makefile
endif
ifeq ($(LE),True)
   include $(AZTPATH)/Src/physics/HD/LE/Makefile
endif
